### ISSUE TITLE
Traduccion de la interfaz

### ISSUE THREAD

**Issue by Framigdom** [Villanueva-del-Trabuco-EGC/decide-part-2#1]
Necesitamos @TheNeoStormZ  y yo que indiqueis por nuestra issue los html que vayais creando.

**Comment by TheNeoStormZ** [comment]
Podeis apuntar los html que habeis modificado o creado tanto en una issue nueva en nuestro repositorio como en esta issue concreta: https://github.com/Villanueva-del-Trabuco-EGC/decide-part-1/issues/1

Si puede ser posible, agadeciriamos que se nos indicaran todos los cambios en la misma issue

**Comment by juacabvil** [comment]
Okay. Dejo una issue en vuestro repositorio para coordinarme con el compañero.
