### ISSUE TITLE
Datos del censo a incluir en el csv

### ISSUE THREAD

**Issue by DiegoRuizGil** [Villanueva-del-Trabuco-EGC/decide-part-2#11]
A la hora de realizar la exportación del censo, ¿qué datos serían relevantes para guardarlos en el csv? Entiendo que para realizar la importación del censo, el único dato relevante es el id de cada usuario, pero considero importante que aparezcan más datos, como podría ser el nombre de usuario, para que el csv sea más legible.
Igualmente podría intentar añadir un selector en la vista de la exportación del censo, para que el usuario elija los  datos que considere necesarios.
@juacabvil

**Comment by juacabvil** [comment]
Para importar el censo, lo imprescindible en cuanto al archivo es que contenga el username y la contraseña de los usuarios que van a entrar al censo. La exportación es una tarea distinta y los datos "necesarios" son un poco más subjetivos. El selector sería una muy buena idea.
