### ISSUE TITLE
Acceso de administradores al censo

### ISSUE THREAD

**Issue by Pabalvcar** [Villanueva-del-Trabuco-EGC/decide-part-2#9]
Como encargado de la autentificación de los usuarios con redes sociales, plantearía que solamente los usuarios con rol de staff/admin sean los que puedan importar y exportar los censos. ¿Qué les parece la idea? @juacabvil @DiegoRuizGil

**Comment by juacabvil** [comment]
Genial. En mi propuesta hice un formulario para usar la cuenta de admin en cuestión, pero comprobar la autoridad directamente me suena más lógico.
